from custom_exceptions.id_not_found import IdNotFound